BOOTLOADER = rp2040
CONVERT_TO = promicro_rp2040

# Features
CAPS_WORD_ENABLE = yes
# COMBO_ENABLE = yes
CUSTOM_ONESHOT_ENABLE = no
EXTRAKEY_ENABLE = no
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = no

# Capabilities
AUDIO_ENABLE = no
BLUETOOTH_ENABLE = no
BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
MIDI_ENABLE = no
MUSIC_ENABLE = no
OLED_ENABLE = no

# Lights
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no    # Enable keyboard RGB underglow
RGBLIGHT_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no
